### ISSUE TITLE
Netflix

### ISSUE THREAD

**Issue by Neos21** [Neos21/Neos21#175]
```css
/* 
 * エンディングで画面を小さくしない
 * https://textuploader.com/dgrt6
 */
.AkiraPlayer .nfp.nf-player-container.NFPlayer.postplay {
  border: 0 solid transparent;
  cursor: default;
  height: 100%;
  left: 0;
  min-height: 160px;
  top: 0;
  width: 100%;
}
.NFPlayer.postplay {
  border: 0 solid #eee;
  height: 100%;
  left: 0;
  top: 0;
  width: 100%;
  z-index: 2;
}
.AkiraPlayer .nfp.nf-player-container.NFPlayer.postplay:hover {
  border: 0 solid #fff;
}

/* シークバーのサムネイル */
.trickplay-text-and-image {
  width: 65px !important;
}

/* シークバーの再生時間 */
.tp-text {
  font-size: 1em !important;
}
```
