### ISSUE TITLE
Amazon Prime Video

### ISSUE THREAD

**Issue by Neos21** [Neos21/Neos21#176]
```css
/* オーバーレイ */
.gradientOverlay,
.pausedOverlay {
  background: transparent !important;
}

/* 再生・移動ボタン */
.buttons {
  position: absolute;
  top: 0;
  left: 0;
}

/* 次のタイトル */
.nextUpWrapper,
.nextUpContents {
  display: none;
}

/* シークバーのサムネイル */
.trickplayImage {
  min-width: 100px !important;
  width: 100px !important;
}

/* シークバーの再生時間 */
.trickplayTime {
  font-size: .75vw !important;
}
```
