### ISSUE TITLE
docker-compose : start and login bash

### ISSUE THREAD

**Issue by Neos21** [Neos21/Neos21#388]
docker-compose で bash に入るには？

```sh
$ docker-compose run SERVICE bash
```

- 参考：[https://sioyaki.com/entry/2016/07/19/194315:title]

考え方

- なんかやる度にコンテナを作ればいい
  - 参考：[https://qiita.com/ka-miyata/items/5dfc03af6d73c8bacc84:title]
  - `$ docker-compose run --rm app npm install` → `$ docker-compose run --rm app npm start` みたいにする
- `stdin_open: true` と `tty: true` の意味が分からん
  - 参考：[https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose:title]
  - `docker-compose up` では Bash に移動しない

フロー

- `docker-compose up -d` で初回起動 : `container_name` が使用される
- `docker exec -it NAME bash` で接続する
  - `docker-compose run` を使う場合は、`container_name` が無視されるので `docker-compose run --name NAME SERVICE bash` と初回起動する
  - 参考：[https://github.com/docker/compose/issues/2061:title]
- 殺さず抜けるには `Ctrl + p` → `Ctrl + q` でデタッチする
  - 続きは `docker exec -it NAME bash` で再開する
- `exit` で抜けたり `docker stop` したりして `Exited` になっているコンテナを再開するには
  - `docker start NAME` → `docker exec -it NAME bash` で再開する

**Comment by Neos21** [comment]
```yaml
version: '3'
services:
  dev:
    container_name: dev
    image: python:3.7.5-buster
    tty: true
    volumes:
      - .:/project
    working_dir: /project
```
