### ISSUE TITLE
VSCode Tree Font

### ISSUE THREAD

**Issue by Neos21** [Neos21/Neos21#966]
https://riosu.hateblo.jp/entry/2018/07/25/230810

**Comment by Neos21** [comment]
```css
.monaco-panel-view,
.label-name {
  font-family: "Noto Sans Mono CJK JP" !important;
}
```

```json
{
  "vscode_custom_css.imports": ["file:///Users/Neo/.vscode/css/styles.css"],
  "vscode_custom_css.policy": true
}
```
